In [1]:
print('hello data analysis')

hello data analysis

In [2]:
def loan_emi(amount, duration,down_payments):
    loan_amount = amount -down_payments
    emi = loan_amount / duration
    
    return emi

In [5]:
loan_emi(10000, 5, 2000)
#using named arguments

loan_emi(amount=10000, duration=8, down_payments=2000)

1000.0

In [6]:
import math
try :
    p = 5/9
    print('The value is ', p)
    print(math.ceil(p))
    
except ZeroDivisionError:
    print('The error is here')

The value is  0.5555555555555556
1

In [7]:
def leisure_cost(return_flight, hotel_per_day, weekly_car_rental,number_of_days,no_weeks):
    hotel_cost = hotel_per_day * number_of_days
    car_cost = weekly_car_rental * no_weeks
    
    total_trip_cost = return_flight + hotel_cost + car_cost
    
    return total_trip_cost

In [26]:
paris = leisure_cost(200,20,200, 7,1)
london = leisure_cost(250, 30, 120, 7, 1)
dubai = leisure_cost(370,15,80, 7, 1)
mumbai = leisure_cost(450, 10, 70, 7, 1)

print(paris,london,dubai,mumbai)
# if paris > london and paris > dubai and paris > mumbai:
#     print(paris)
    
# elif london > paris and london > dubai and london > mumbai:
#     print(london)
    
# elif dubai > paris and dubai > london and dubai > mumbai:
#     print(dubai)
    
# elif mumbai > paris and mumbai > dubai and mumbai > mumbai:
#     print(mumbai)
# else:
#     print("The value cant be found")
paris = leisure_cost(200,20,200, 4,0)
london = leisure_cost(250, 30, 120, 4,0)
dubai = leisure_cost(370,15,80, 4,0)
mumbai = leisure_cost(450, 10, 70, 4,0)

print(paris,london,dubai,mumbai)

paris = leisure_cost(200,20,200, 10,0)
london = leisure_cost(250, 30, 120, 10,0)
dubai = leisure_cost(370,15,80, 10,0)
mumbai = leisure_cost(450, 10, 70, 10,0)

print(paris,london,dubai,mumbai)

paris = leisure_cost(200,20,200, 14,2)
london = leisure_cost(250, 30, 120, 14,2)
dubai = leisure_cost(370,15,80, 14,2)
mumbai = leisure_cost(450, 10, 70, 14,2)

print("The values are {} and {} and {} and {} ".format(paris,london,dubai,mumbai))

540 580 555 590
280 370 430 490
400 550 520 550
The values are 880 and 910 and 740 and 730

In [22]:
help (format)

Help on built-in function format in module builtins:

format(value, format_spec='', /)
    Return value.__format__(format_spec)

    format_spec defaults to the empty string.
    See the Format Specification Mini-Language section of help('FORMATTING') for
    details.

In [1]:
help('FORMATTING')

Format String Syntax
********************

The "str.format()" method and the "Formatter" class share the same
syntax for format strings (although in the case of "Formatter",
subclasses can define their own format string syntax).  The syntax is
related to that of formatted string literals, but there are
differences.

Format strings contain “replacement fields” surrounded by curly braces
"{}". Anything that is not contained in braces is considered literal
text, which is copied unchanged to the output.  If you need to include
a brace character in the literal text, it can be escaped by doubling:
"{{" and "}}".

The grammar for a replacement field is as follows:

      replacement_field ::= "{" [field_name] ["!" conversion] [":" format_spec] "}"
      field_name        ::= arg_name ("." attribute_name | "[" element_index "]")*
      arg_name          ::= [identifier | digit+]
      attribute_name    ::= identifier
      element_index     ::= digit+ | index_string
      index_string      ::= <any source character except "]"> +
      conversion        ::= "r" | "s" | "a"
      format_spec       ::= <described in the next section>

In less formal terms, the replacement field can start with a
*field_name* that specifies the object whose value is to be formatted
and inserted into the output instead of the replacement field. The
*field_name* is optionally followed by a  *conversion* field, which is
preceded by an exclamation point "'!'", and a *format_spec*, which is
preceded by a colon "':'".  These specify a non-default format for the
replacement value.

See also the Format Specification Mini-Language section.

The *field_name* itself begins with an *arg_name* that is either a
number or a keyword.  If it’s a number, it refers to a positional
argument, and if it’s a keyword, it refers to a named keyword
argument.  If the numerical arg_names in a format string are 0, 1, 2,
… in sequence, they can all be omitted (not just some) and the numbers
0, 1, 2, … will be automatically inserted in that order. Because
*arg_name* is not quote-delimited, it is not possible to specify
arbitrary dictionary keys (e.g., the strings "'10'" or "':-]'") within
a format string. The *arg_name* can be followed by any number of index
or attribute expressions. An expression of the form "'.name'" selects
the named attribute using "getattr()", while an expression of the form
"'[index]'" does an index lookup using "__getitem__()".

Changed in version 3.1: The positional argument specifiers can be
omitted for "str.format()", so "'{} {}'.format(a, b)" is equivalent to
"'{0} {1}'.format(a, b)".

Changed in version 3.4: The positional argument specifiers can be
omitted for "Formatter".

Some simple format string examples:

   "First, thou shalt count to {0}"  # References first positional argument
   "Bring me a {}"                   # Implicitly references the first positional argument
   "From {} to {}"                   # Same as "From {0} to {1}"
   "My quest is {name}"              # References keyword argument 'name'
   "Weight in tons {0.weight}"       # 'weight' attribute of first positional arg
   "Units destroyed: {players[0]}"   # First element of keyword argument 'players'.

The *conversion* field causes a type coercion before formatting.
Normally, the job of formatting a value is done by the "__format__()"
method of the value itself.  However, in some cases it is desirable to
force a type to be formatted as a string, overriding its own
definition of formatting.  By converting the value to a string before
calling "__format__()", the normal formatting logic is bypassed.

Three conversion flags are currently supported: "'!s'" which calls
"str()" on the value, "'!r'" which calls "repr()" and "'!a'" which
calls "ascii()".

Some examples:

   "Harold's a clever {0!s}"        # Calls str() on the argument first
   "Bring out the holy {name!r}"    # Calls repr() on the argument first
   "More {!a}"                      # Calls ascii() on the argument first

The *format_spec* field contains a specification of how the value
should be presented, including such details as field width, alignment,
padding, decimal precision and so on.  Each value type can define its
own “formatting mini-language” or interpretation of the *format_spec*.

Most built-in types support a common formatting mini-language, which
is described in the next section.

A *format_spec* field can also include nested replacement fields
within it. These nested replacement fields may contain a field name,
conversion flag and format specification, but deeper nesting is not
allowed.  The replacement fields within the format_spec are
substituted before the *format_spec* string is interpreted. This
allows the formatting of a value to be dynamically specified.

See the Format examples section for some examples.


Format Specification Mini-Language
==================================

“Format specifications” are used within replacement fields contained
within a format string to define how individual values are presented
(see Format String Syntax and Formatted string literals). They can
also be passed directly to the built-in "format()" function.  Each
formattable type may define how the format specification is to be
interpreted.

Most built-in types implement the following options for format
specifications, although some of the formatting options are only
supported by the numeric types.

A general convention is that an empty format specification produces
the same result as if you had called "str()" on the value. A non-empty
format specification typically modifies the result.

The general form of a *standard format specifier* is:

   format_spec     ::= [[fill]align][sign][#][0][width][grouping_option][.precision][type]
   fill            ::= <any character>
   align           ::= "<" | ">" | "=" | "^"
   sign            ::= "+" | "-" | " "
   width           ::= digit+
   grouping_option ::= "_" | ","
   precision       ::= digit+
   type            ::= "b" | "c" | "d" | "e" | "E" | "f" | "F" | "g" | "G" | "n" | "o" | "s" | "x" | "X" | "%"

If a valid *align* value is specified, it can be preceded by a *fill*
character that can be any character and defaults to a space if
omitted. It is not possible to use a literal curly brace (“"{"” or
“"}"”) as the *fill* character in a formatted string literal or when
using the "str.format()" method.  However, it is possible to insert a
curly brace with a nested replacement field.  This limitation doesn’t
affect the "format()" function.

The meaning of the various alignment options is as follows:

   +-----------+------------------------------------------------------------+
   | Option    | Meaning                                                    |
   |===========|============================================================|
   | "'<'"     | Forces the field to be left-aligned within the available   |
   |           | space (this is the default for most objects).              |
   +-----------+------------------------------------------------------------+
   | "'>'"     | Forces the field to be right-aligned within the available  |
   |           | space (this is the default for numbers).                   |
   +-----------+------------------------------------------------------------+
   | "'='"     | Forces the padding to be placed after the sign (if any)    |
   |           | but before the digits.  This is used for printing fields   |
   |           | in the form ‘+000000120’. This alignment option is only    |
   |           | valid for numeric types.  It becomes the default when ‘0’  |
   |           | immediately precedes the field width.                      |
   +-----------+------------------------------------------------------------+
   | "'^'"     | Forces the field to be centered within the available       |
   |           | space.                                                     |
   +-----------+------------------------------------------------------------+

Note that unless a minimum field width is defined, the field width
will always be the same size as the data to fill it, so that the
alignment option has no meaning in this case.

The *sign* option is only valid for number types, and can be one of
the following:

   +-----------+------------------------------------------------------------+
   | Option    | Meaning                                                    |
   |===========|============================================================|
   | "'+'"     | indicates that a sign should be used for both positive as  |
   |           | well as negative numbers.                                  |
   +-----------+------------------------------------------------------------+
   | "'-'"     | indicates that a sign should be used only for negative     |
   |           | numbers (this is the default behavior).                    |
   +-----------+------------------------------------------------------------+
   | space     | indicates that a leading space should be used on positive  |
   |           | numbers, and a minus sign on negative numbers.             |
   +-----------+------------------------------------------------------------+

The "'#'" option causes the “alternate form” to be used for the
conversion.  The alternate form is defined differently for different
types.  This option is only valid for integer, float, complex and
Decimal types. For integers, when binary, octal, or hexadecimal output
is used, this option adds the prefix respective "'0b'", "'0o'", or
"'0x'" to the output value. For floats, complex and Decimal the
alternate form causes the result of the conversion to always contain a
decimal-point character, even if no digits follow it. Normally, a
decimal-point character appears in the result of these conversions
only if a digit follows it. In addition, for "'g'" and "'G'"
conversions, trailing zeros are not removed from the result.

The "','" option signals the use of a comma for a thousands separator.
For a locale aware separator, use the "'n'" integer presentation type
instead.

Changed in version 3.1: Added the "','" option (see also **PEP 378**).

The "'_'" option signals the use of an underscore for a thousands
separator for floating point presentation types and for integer
presentation type "'d'".  For integer presentation types "'b'", "'o'",
"'x'", and "'X'", underscores will be inserted every 4 digits.  For
other presentation types, specifying this option is an error.

Changed in version 3.6: Added the "'_'" option (see also **PEP 515**).

*width* is a decimal integer defining the minimum total field width,
including any prefixes, separators, and other formatting characters.
If not specified, then the field width will be determined by the
content.

When no explicit alignment is given, preceding the *width* field by a
zero ("'0'") character enables sign-aware zero-padding for numeric
types.  This is equivalent to a *fill* character of "'0'" with an
*alignment* type of "'='".

The *precision* is a decimal number indicating how many digits should
be displayed after the decimal point for a floating point value
formatted with "'f'" and "'F'", or before and after the decimal point
for a floating point value formatted with "'g'" or "'G'".  For non-
number types the field indicates the maximum field size - in other
words, how many characters will be used from the field content. The
*precision* is not allowed for integer values.

Finally, the *type* determines how the data should be presented.

The available string presentation types are:

   +-----------+------------------------------------------------------------+
   | Type      | Meaning                                                    |
   |===========|============================================================|
   | "'s'"     | String format. This is the default type for strings and    |
   |           | may be omitted.                                            |
   +-----------+------------------------------------------------------------+
   | None      | The same as "'s'".                                         |
   +-----------+------------------------------------------------------------+

The available integer presentation types are:

   +-----------+------------------------------------------------------------+
   | Type      | Meaning                                                    |
   |===========|============================================================|
   | "'b'"     | Binary format. Outputs the number in base 2.               |
   +-----------+------------------------------------------------------------+
   | "'c'"     | Character. Converts the integer to the corresponding       |
   |           | unicode character before printing.                         |
   +-----------+------------------------------------------------------------+
   | "'d'"     | Decimal Integer. Outputs the number in base 10.            |
   +-----------+------------------------------------------------------------+
   | "'o'"     | Octal format. Outputs the number in base 8.                |
   +-----------+------------------------------------------------------------+
   | "'x'"     | Hex format. Outputs the number in base 16, using lower-    |
   |           | case letters for the digits above 9.                       |
   +-----------+------------------------------------------------------------+
   | "'X'"     | Hex format. Outputs the number in base 16, using upper-    |
   |           | case letters for the digits above 9.                       |
   +-----------+------------------------------------------------------------+
   | "'n'"     | Number. This is the same as "'d'", except that it uses the |
   |           | current locale setting to insert the appropriate number    |
   |           | separator characters.                                      |
   +-----------+------------------------------------------------------------+
   | None      | The same as "'d'".                                         |
   +-----------+------------------------------------------------------------+

In addition to the above presentation types, integers can be formatted
with the floating point presentation types listed below (except "'n'"
and "None"). When doing so, "float()" is used to convert the integer
to a floating point number before formatting.

The available presentation types for floating point and decimal values
are:

   +-----------+------------------------------------------------------------+
   | Type      | Meaning                                                    |
   |===========|============================================================|
   | "'e'"     | Exponent notation. Prints the number in scientific         |
   |           | notation using the letter ‘e’ to indicate the exponent.    |
   |           | The default precision is "6".                              |
   +-----------+------------------------------------------------------------+
   | "'E'"     | Exponent notation. Same as "'e'" except it uses an upper   |
   |           | case ‘E’ as the separator character.                       |
   +-----------+------------------------------------------------------------+
   | "'f'"     | Fixed-point notation. Displays the number as a fixed-point |
   |           | number. The default precision is "6".                      |
   +-----------+------------------------------------------------------------+
   | "'F'"     | Fixed-point notation. Same as "'f'", but converts "nan" to |
   |           | "NAN" and "inf" to "INF".                                  |
   +-----------+------------------------------------------------------------+
   | "'g'"     | General format.  For a given precision "p >= 1", this      |
   |           | rounds the number to "p" significant digits and then       |
   |           | formats the result in either fixed-point format or in      |
   |           | scientific notation, depending on its magnitude.  The      |
   |           | precise rules are as follows: suppose that the result      |
   |           | formatted with presentation type "'e'" and precision "p-1" |
   |           | would have exponent "exp".  Then, if "m <= exp < p", where |
   |           | "m" is -4 for floats and -6 for "Decimals", the number is  |
   |           | formatted with presentation type "'f'" and precision       |
   |           | "p-1-exp".  Otherwise, the number is formatted with        |
   |           | presentation type "'e'" and precision "p-1". In both cases |
   |           | insignificant trailing zeros are removed from the          |
   |           | significand, and the decimal point is also removed if      |
   |           | there are no remaining digits following it, unless the     |
   |           | "'#'" option is used.  Positive and negative infinity,     |
   |           | positive and negative zero, and nans, are formatted as     |
   |           | "inf", "-inf", "0", "-0" and "nan" respectively,           |
   |           | regardless of the precision.  A precision of "0" is        |
   |           | treated as equivalent to a precision of "1". The default   |
   |           | precision is "6".                                          |
   +-----------+------------------------------------------------------------+
   | "'G'"     | General format. Same as "'g'" except switches to "'E'" if  |
   |           | the number gets too large. The representations of infinity |
   |           | and NaN are uppercased, too.                               |
   +-----------+------------------------------------------------------------+
   | "'n'"     | Number. This is the same as "'g'", except that it uses the |
   |           | current locale setting to insert the appropriate number    |
   |           | separator characters.                                      |
   +-----------+------------------------------------------------------------+
   | "'%'"     | Percentage. Multiplies the number by 100 and displays in   |
   |           | fixed ("'f'") format, followed by a percent sign.          |
   +-----------+------------------------------------------------------------+
   | None      | Similar to "'g'", except that fixed-point notation, when   |
   |           | used, has at least one digit past the decimal point. The   |
   |           | default precision is as high as needed to represent the    |
   |           | particular value. The overall effect is to match the       |
   |           | output of "str()" as altered by the other format           |
   |           | modifiers.                                                 |
   +-----------+------------------------------------------------------------+


Format examples
===============

This section contains examples of the "str.format()" syntax and
comparison with the old "%"-formatting.

In most of the cases the syntax is similar to the old "%"-formatting,
with the addition of the "{}" and with ":" used instead of "%". For
example, "'%03.2f'" can be translated to "'{:03.2f}'".

The new format syntax also supports new and different options, shown
in the following examples.

Accessing arguments by position:

   >>> '{0}, {1}, {2}'.format('a', 'b', 'c')
   'a, b, c'
   >>> '{}, {}, {}'.format('a', 'b', 'c')  # 3.1+ only
   'a, b, c'
   >>> '{2}, {1}, {0}'.format('a', 'b', 'c')
   'c, b, a'
   >>> '{2}, {1}, {0}'.format(*'abc')      # unpacking argument sequence
   'c, b, a'
   >>> '{0}{1}{0}'.format('abra', 'cad')   # arguments' indices can be repeated
   'abracadabra'

Accessing arguments by name:

   >>> 'Coordinates: {latitude}, {longitude}'.format(latitude='37.24N', longitude='-115.81W')
   'Coordinates: 37.24N, -115.81W'
   >>> coord = {'latitude': '37.24N', 'longitude': '-115.81W'}
   >>> 'Coordinates: {latitude}, {longitude}'.format(**coord)
   'Coordinates: 37.24N, -115.81W'

Accessing arguments’ attributes:

   >>> c = 3-5j
   >>> ('The complex number {0} is formed from the real part {0.real} '

In [27]:
%%time

print("hello")

hello
CPU times: user 118 µs, sys: 7 µs, total: 125 µs
Wall time: 99.7 µs

In [30]:
%%time
for k in range(2, 8):
    print(k)

2
3
4
5
6
7
CPU times: user 612 µs, sys: 67 µs, total: 679 µs
Wall time: 399 µs

In [34]:
!ls
# !cat hert.txt
!cat newdata.txt

 datacleaning.ipynb			       pandasIntro1.ipynb
 DataSets				       president.csv
 datastructures2.ipynb			      'ql -u root -p'
 datastructures.ipynb			       SAmatlab_09.pdf
 dates.csv				       senate.csv
 exercise1.ipynb			       sys
 heart.csv				       test1.ipynb
 heartResults.txt			       test2.ipynb
 hert.txt				       Untitled1.ipynb
 intro-data-analysis.ipynb		       Untitled2.ipynb
'IO tools.ipynb'			       Untitled3.ipynb
 Matplotlib.ipynb			       Untitled5.ipynb
 mysql80-community-release-sl15-3.noarch.rpm   Untitled.ipynb
 newdata.txt				       untitled.md
920487.0000 11128.0000 15735.0000 2181676.0000 4087084.0000 2565.0000 8531.0000 2440096.0000 5507.0000 17794.2000 22766.0000 12790.0000 38225.0000 8662.0000
11128.0000 207.0000 193.0000 27106.0000 49533.0000 33.0000 105.0000 30835.0000 77.0000 230.9000 287.0000 168.0000 497.0000 93.0000
15735.0000 193.0000 605.0000 38826.0000 70913.0000 54.0000 162.0000 45958.0000 38.0000 250.6000 433.0000 156.0000 647.0000 227.0000
2181676.0000 27106.0000 38826.0000 5342310.0000 9855316.0000 6258.0000 20742.0000 5962551.0000 13199.0000 42649.7000 55412.0000 29638.0000 92470.0000 21335.0000
4087084.0000 49533.0000 70913.0000 9855316.0000 19187030.0000 11156.0000 38159.0000 11162786.0000 24873.0000 78553.7000 104377.0000 55553.0000 173578.0000 39968.0000
2565.0000 33.0000 54.0000 6258.0000 11156.0000 45.0000 19.0000 6713.0000 16.0000 47.5000 59.0000 48.0000 102.0000 23.0000
8531.0000 105.0000 162.0000 20742.0000 38159.0000 19.0000 168.0000 24104.0000 47.0000 155.5000 233.0000 105.0000 369.0000 98.0000
2440096.0000 30835.0000 45958.0000 5962551.0000 11162786.0000 6713.0000 24104.0000 6943881.0000 13584.0000 44374.4000 65099.0000 31564.0000 104494.0000 26147.0000
5507.0000 77.0000 38.0000 13199.0000 24873.0000 16.0000 47.0000 13584.0000 99.0000 150.4000 116.0000 89.0000 247.0000 23.0000
17794.2000 230.9000 250.6000 42649.7000 78553.7000 47.5000 155.5000 44374.4000 150.4000 734.6000 316.0000 309.6000 773.9000 96.2000
22766.0000 287.0000 433.0000 55412.0000 104377.0000 59.0000 233.0000 65099.0000 116.0000 316.0000 708.0000 294.0000 969.0000 263.0000
12790.0000 168.0000 156.0000 29638.0000 55553.0000 48.0000 105.0000 31564.0000 89.0000 309.6000 294.0000 477.0000 540.0000 60.0000
38225.0000 497.0000 647.0000 92470.0000 173578.0000 102.0000 369.0000 104494.0000 247.0000 773.9000 969.0000 540.0000 1735.0000 350.0000
8662.0000 93.0000 227.0000 21335.0000 39968.0000 23.0000 98.0000 26147.0000 23.0000 96.2000 263.0000 60.0000 350.0000 165.0000
4496911.4240 55321.9046 79361.8796 10900566.8815 20706842.1500 12510.9390 42544.5117 12323460.7700 27057.0005 86663.2835 115029.6530 61121.0315 190861.4939 44320.5793

In [56]:
import urllib.request as r
import numpy as np

data = np.genfromtxt('hert.txt', delimiter=',', skip_header=1)
data
#data shape
data.shape
# weights = np.array([0.3, 0.2, 0.4])
weights = np.random.rand(14)
yields = data @ weights
yields
yields.shape
# adding the yields to the data
results = np.concatenate((data,yields.reshape(303,1)), axis=1)
results
np.savetxt('heartResults.txt', results, fmt='%.2f')

results.shape
newresult = results.T
newresult.shape
newdata = newresult @ data
np.savetxt('newdata.txt', newdata, fmt='%.4f')
minimum = newdata.min()
minimum
maximum = newdata.max()
maximum

data_range = maximum - minimum
data_range
round(data_range, 2)
data.sum()
data.mean().round(2) 


newresult.shape
newresult.reshape(9,5,101)
newresult.ndim
newresult.size
newresult[0].sum()
newresult[0:3].sum()

16973.0

In [59]:
!ls

file = open('senate.csv')
file

 datacleaning.ipynb			       pandasIntro1.ipynb
 DataSets				       president.csv
 datastructures2.ipynb			      'ql -u root -p'
 datastructures.ipynb			       SAmatlab_09.pdf
 dates.csv				       senate.csv
 exercise1.ipynb			       sys
 heart.csv				       test1.ipynb
 heartResults.txt			       test2.ipynb
 hert.txt				       Untitled1.ipynb
 intro-data-analysis.ipynb		       Untitled2.ipynb
'IO tools.ipynb'			       Untitled3.ipynb
 Matplotlib.ipynb			       Untitled5.ipynb
 mysql80-community-release-sl15-3.noarch.rpm   Untitled.ipynb
 newdata.txt				       untitled.md

In [77]:
#opening the file
file = open('heart.csv', mode='r')
file
# reading the file using the read()- function
fileContents = file.read()
fileContents
file.close()

with open('heart.csv', mode='r') as file2:
    file_contents2 = file2.read()
    print(file_contents2)

In [121]:
listdata = []
with open('heart.csv', mode='r') as file3:
    file_contents3 = file3.readlines()
    
    #print(file_contents3[1])
    
    for k in file_contents3:
        #print(k.split(','))
        listdata.append(k.split(','))
    #print(listdata)
    
    mydata = np.array(listdata)
    print(mydata)
    print(mydata.shape)
    
    #print(listdata)
    
    import pandas as pd
    
df = pd.DataFrame(listdata)
df.head(50).describe()
df.info()
df.describe()
df[0][1:-1]

[['age' 'sex' 'cp' ... 'caa' 'thall' 'output\n']
 ['63' '1' '3' ... '0' '1' '1\n']
 ['37' '1' '2' ... '0' '2' '1\n']
 ...
 ['68' '1' '0' ... '2' '3' '0\n']
 ['57' '1' '0' ... '1' '3' '0\n']
 ['57' '0' '1' ... '1' '2' '0\n']]
(304, 14)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 304 entries, 0 to 303
Data columns (total 14 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       304 non-null    object
 1   1       304 non-null    object
 2   2       304 non-null    object
 3   3       304 non-null    object
 4   4       304 non-null    object
 5   5       304 non-null    object
 6   6       304 non-null    object
 7   7       304 non-null    object
 8   8       304 non-null    object
 9   9       304 non-null    object
 10  10      304 non-null    object
 11  11      304 non-null    object
 12  12      304 non-null    object
 13  13      304 non-null    object
dtypes: object(14)
memory usage: 33.4+ KB

1      63
2      37
3      41
4      56
5      57
       ..
298    59
299    57
300    45
301    68
302    57
Name: 0, Length: 302, dtype: object

In [190]:
k = '56666, 78899, 8999, 89080'
k.strip().split(',')

['56666', ' 78899', ' 8999', ' 89080']

In [204]:
def loan_emi(amount, duration,rate,down_payments):
    loan_amount = amount -down_payments
    emi = loan_amount / duration
    
    return emi

loans= [{ 'amount':828400,'duration': 120,'rate':0.11,'down_payment':100000},
        { 'amount':4633400,'duration': 240,'rate':0.06,'down_payment':0},
        { 'amount':42900,'duration': 90,'rate':0.08,'down_payment':8900},
        { 'amount':983000,'duration': 16,'rate':0.14,'down_payment':0},
        { 'amount':15230,'duration': 48,'rate':0.07,'down_payment':4300}]

values = []
for loan in loans:
    print(loan['amount'], loan['duration'], loan['rate'], loan['down_payment'])

    
    emi = loan_emi(loan['amount'],loan['duration'],loan['rate'], loan['down_payment'])  
    amount = round(loan['amount'])
    duration = round(loan['duration'])
    rate = round(loan['rate'])
    down_payment = round(loan['down_payment'])
    values.append(emi)
# print(values)

    file = open('loans.txt', mode='w')
    file.write('{},{}, {},{} \n'.format(amount,duration,rate,down_payment,emi))
file.close()

828400 120 0.11 100000
4633400 240 0.06 0
42900 90 0.08 8900
983000 16 0.14 0
15230 48 0.07 4300

In [125]:

with open('heart.csv', mode='r') as file4:
    file_contents3 = file4.readlines()
    
    print(file_contents3[1])

63,1,3,145,233,1,0,150,0,2.3,0,0,1,1

In [163]:
# help(zip)
zipped = []
h = [234,2,3,3,4,4]
p = [90, 567,6,678,90, 89]
l = [20,34,46,47,78, 90]

k = zip(h,p)
k1 = zip(k,l)
print(k)
for i,m in k1:
    
    #print(i,m)
    
    for h in i:
        print('hhh',h)
        e =  h + m
        zipped.append(e)
print(zipped)

<zip object at 0x7fb509c30b40>
hhh 234
hhh 90
hhh 2
hhh 567
hhh 3
hhh 6
hhh 3
hhh 678
hhh 4
hhh 90
hhh 4
hhh 89
[254, 110, 36, 601, 49, 52, 50, 725, 82, 168, 94, 179]

In [176]:
def read_csv(path):
    result = []
    with open (path, mode='r') as file5:
        lines = file5.readlines()
        #print(lines)
        headers = lines[0]
        print(headers)
        
read_csv('hert.txt')

age,sex,cp,trtbps,chol,fbs,restecg,thalachh,exng,oldpeak,slp,caa,thall,output

In [206]:
import pandas as pd
netflix = pd.read_csv('netflix_titles.csv')
netflix.head(110)
# netflix

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,TV Show,3%,NaN,"João Miguel, Bianca Comparato, Michel Gomes, R...",Brazil,"August 14, 2020",2020,TV-MA,4 Seasons,"International TV Shows, TV Dramas, TV Sci-Fi &...",In a future where the elite inhabit an island ...
1,s2,Movie,7:19,Jorge Michel Grau,"Demián Bichir, Héctor Bonilla, Oscar Serrano, ...",Mexico,"December 23, 2016",2016,TV-MA,93 min,"Dramas, International Movies",After a devastating earthquake hits Mexico Cit...
2,s3,Movie,23:59,Gilbert Chan,"Tedd Chan, Stella Chung, Henley Hii, Lawrence ...",Singapore,"December 20, 2018",2011,R,78 min,"Horror Movies, International Movies","When an army recruit is found dead, his fellow..."
3,s4,Movie,9,Shane Acker,"Elijah Wood, John C. Reilly, Jennifer Connelly...",United States,"November 16, 2017",2009,PG-13,80 min,"Action & Adventure, Independent Movies, Sci-Fi...","In a postapocalyptic world, rag-doll robots hi..."
4,s5,Movie,21,Robert Luketic,"Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...",United States,"January 1, 2020",2008,PG-13,123 min,Dramas,A brilliant group of students become card-coun...
...,...,...,...,...,...,...,...,...,...,...,...,...
105,s106,Movie,300 Miles to Heaven,Maciej Dejczer,"Krzysztof Stroiński, Andrzej Mellin, Adrianna ...","Denmark, France, Poland","October 1, 2019",1989,TV-14,93 min,"Dramas, International Movies","Hoping to help their dissident parents, two br..."
106,s107,Movie,365 Days,"Barbara Białowąs, Tomasz Mandes","Anna-Maria Sieklucka, Michele Morrone, Bronisł...",Poland,"June 7, 2020",2020,TV-MA,114 min,"Dramas, International Movies, Romantic Movies",A fiery executive in a spiritless relationship...
107,s108,Movie,37 Seconds,Hikari,"Mei Kayama, Misuzu Kanno, Shunsuke Daitoh, Mak...",Japan,"January 31, 2020",2020,TV-MA,116 min,"Dramas, International Movies","Trapped by society and familial obligations, a..."
108,s109,TV Show,3Below: Tales of Arcadia,NaN,"Tatiana Maslany, Diego Luna, Nick Offerman, Ni...",United States,"July 12, 2019",2019,TV-Y7,2 Seasons,"Kids' TV, TV Action & Adventure, TV Sci-Fi & F...","After crash-landing on Earth, two royal teen a..."
109,s110,Movie,40 Sticks,Victor Gatonye,"Robert Agengo, Mwaura Bilal, Andreo Kamau, Caj...",Kenya,"November 20, 2020",2019,TV-14,93 min,"International Movies, Thrillers",When their prison bus crashes in a forest on a...

In [189]:
#help(parse_header)

In [199]:
p = 67.890
round(p)

68